### ISSUE TITLE
Make login/register in React communicate with the server

### ISSUE THREAD

**Issue by hassan-bazzi** [deepditch/deep.web#19]
I think we need to use Redux for maintaining state:

http://jasonwatmore.com/post/2017/12/07/react-redux-jwt-authentication-tutorial-example

@drakesvoboda let me know what your ideas are for this

**Comment by drakesvoboda** [comment]
Take a look at 0695a29 and 
https://medium.com/@magnusjt/dependency-injection-in-nodejs-9601a19c1f36
https://medium.com/@magnusjt/ioc-container-in-nodejs-e7aea8a89600
https://medium.com/@magnusjt/inversion-of-control-and-di-in-reactjs-and-redux-35161fcef847

**Comment by drakesvoboda** [comment]
Resolved by #24
