### ISSUE TITLE
Basic Front End

### ISSUE THREAD

**Issue by drakesvoboda** [deepditch/deep.web#3]
Setup a React.js front end for the web application

**Comment by drakesvoboda** [comment]
Started a [branch](https://github.com/deepditch/deep.web/tree/feature/basic-front-end/3) for this. I'll need to write some docs for getting the front end dependencies installed

**Comment by hassan-bazzi** [comment]
Progress was made for this on #4

**Comment by hassan-bazzi** [comment]
I'm going to close this out. I think further progress on frontend should be split up into new issues
