### ISSUE TITLE
Refactor damages in the database into reports + damages

### ISSUE THREAD

**Issue by hassan-bazzi** [deepditch/deep.web#48]
Drake [8:42 PM]
Should we create a second table in the database, one for damage instances and one for reports. A damage instance could have one or more reports. A report has only one image
A report could have multiple damage types, or no damage types if we are reporting a potential false positive
Then when new reports come in, they would be added to the reports table and those reports would be assigned to either an existing damage instance or a new damage instance would be created

Hassan Bazzi [8:45 PM]
that makes sense to me
will open an issue to make that happen

Drake [8:47 PM]
Cool. Not sure who should be responsible for holding the location data. Probably both tables

Hassan Bazzi [8:48 PM]
i don't think that's necessary, we can just have location in the damage row and that's how we'll determine if we need a new damage created or not
if we already have a damage at this location use that, else create one
then we can do like get me all reports for this location

Drake [8:48 PM]
Well, it might be valuable to store the raw data for each report
Because it is going to be (theoretically) impossible to have two reports at exactly the same location
Due to the nature of lat lng

Hassan Bazzi [8:50 PM]
i see yeah that makes sense

Drake [8:50 PM]
So there needs to be some tolerance for when a new report gets assigned to an old damage

Hassan Bazzi [8:53 PM]
when we do this I think damage type on the road damage instance in the DB won't be needed, road damage would then represent more of a location than anything and damage type(s) at that location (including whatever threshold we include) would be determined by the associated reports

Drake [8:54 PM]
Would that make filtering by type more difficult?

Hassan Bazzi [8:56 PM]
I don't think so because the type(s) would still be in the RoadDamage resource json we get back from the api, they'll just be determined by the reports

Drake [8:58 PM]
I think that will work

**Comment by drakesvoboda** [comment]
I think the report upload data should look like the following:
```
{
  image: ...,
  location: { 
    latitude: ..., 
    longitude: ...
  },
  direction: <vehicles heading>,
  damages: [
    {
      type: ...,
      confidence: <value between [0,1]>
    },
    ...
  ]
}
```
Not sure what direction entails
